### ISSUE TITLE
Show all users

### ISSUE THREAD

**Issue by ghost** [ramzialhaddadtm/discord-data-package-viewer-parser#2]
Just wanted to ask if this was going to be updated anytime soon to show every single user you have ever dmd in the side panel. because this would be such a life saver once it does.

**Comment by ramzialhaddad** [comment]
hey @wick78,

To be quite honest I am not sure when or if it will ever be updated, I do have other projects to work on and quite busy with school and the likes. If I find some motivation and free time then I might spend time updating this but for the time being, I recommend this repository.

https://github.com/HyperGabe/Discord-Data-Package-Parser

It will get the job done as far as I know

**Comment by ghost** [comment]
Thank you so much for such a quick response, that file you showed me has no
executable file and i cant figure out how to run it,

**Comment by ramzialhaddad** [comment]
Oh sorry about that, that was just the repository.

https://github.com/HyperGabe/Discord-Data-Package-Parser/releases/download/v1.0/DDPP.exe

This is the executable file itself but do read 
![image](https://user-images.githubusercontent.com/5371012/65628879-f7164b80-df97-11e9-8d82-68e8eddeda11.png) So you can understand how to execute it!

**Comment by ghost** [comment]
Thankyou very much I did figure it out but I appreciate you messaging back.
Just one last question if you don’t mind this application you sent me will
show every single person you ever sent a direct message to on that account
? And if it’s not  in there it was deleted or you never sent a person a
direct message.

**Comment by ramzialhaddad** [comment]
It will show everything that is not deleted up to the point of when you requested your data. So if you message someone after when you requested it then it probably won't show.

**Comment by ghost** [comment]
Thankyou so much I can’t tell you enough how much I appreciate your help.
You did an amazing job on this program. Do you plan on doing any further
updating to show more of the data package ?

**Comment by ramzialhaddad** [comment]
Thank you for your kind words. I might eventually touch it up but I really can't say for sure.
